### ISSUE TITLE
Blender 2.9 ?

### ISSUE THREAD

**Issue by pr0eXeler0** [vncastanheira/Blender-MDL-Exporter#3]
Ok, its pretty obvious that this isnt frequently updated ;-) buuuut it would be super useful if this worked with Blender 2.8/9

**Comment by vncastanheira** [comment]
Yeah, this is gonna be complicated. 
This repo is more like a resource to keep the plugin alive but right now I can't afford the time to update it though.
If anyone wants to do it, it's open for contribution.

**Comment by vncastanheira** [comment]
@pr0eXeler0 Hey, if you're still interested, you can use it now on the 2.93LTS branch.
https://github.com/vncastanheira/Blender-MDL-Exporter/tree/2.93LTS

Just downlod the repository as zip file and import into Blender.
