### ISSUE TITLE
Blender 3.3 No modul named

### ISSUE THREAD

**Issue by MisterZ808** [vncastanheira/Blender-MDL-Exporter#4]
so i install the addon and  it shows up but atfter i click the chekbox it says

Traceback (most recent call last):
  File "E:\Blender\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Blender-MDL-Exporter-2.83'

sometimes it shows
Traceback (most recent call last):
  File "E:\Blender\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Blender-MDL-Exporter-2'

so i tryed to change the number of the folder then the number 2 dosnt show in the error log, then it shows 2.83, so
i change it back and then it shows me the correct error with 2.83...

**Comment by vncastanheira** [comment]
I'll take a look on this.

**Comment by vncastanheira** [comment]
> so i install the addon and it shows up but atfter i click the chekbox it says
> 
> Traceback (most recent call last): File "E:\Blender\3.3\scripts\modules\addon_utils.py", line 333, in enable mod = **import**(module_name) ModuleNotFoundError: No module named 'Blender-MDL-Exporter-2.83'
> 
> sometimes it shows Traceback (most recent call last): File "E:\Blender\3.3\scripts\modules\addon_utils.py", line 333, in enable mod = **import**(module_name) ModuleNotFoundError: No module named 'Blender-MDL-Exporter-2'
> 
> so i tryed to change the number of the folder then the number 2 dosnt show in the error log, then it shows 2.83, so i change it back and then it shows me the correct error with 2.83...

I found that there was an issue when downloading a ZIP from the branches, as Github is renaming the contained folder inside and inserting the branch name, then causing this problem.

Try getting from the Release page now:
https://github.com/vncastanheira/Blender-MDL-Exporter/releases/tag/2.8

**Comment by MisterZ808** [comment]
thanks , not its working
